// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgm1xq5uj2oixigswvvIv4zt_dKdX7HiU',
    appId: '1:276637643929:web:713b7c2a9a9a87322c7408',
    messagingSenderId: '276637643929',
    projectId: 'zerotouchrescue',
    authDomain: 'zerotouchrescue.firebaseapp.com',
    databaseURL: 'https://zerotouchrescue-default-rtdb.firebaseio.com',
    storageBucket: 'zerotouchrescue.firebasestorage.app',
    measurementId: 'G-XJMDDXHDP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqo9qTChHUAT493okfZ7PZ2sXdpgjSw_Y',
    appId: '1:450401377621:android:9dc1abd308f38fc53363dc',
    messagingSenderId: '450401377621',
    projectId: 'zerotouchrescuenew-14125',
    storageBucket: 'zerotouchrescuenew-14125.firebasestorage.app',
  );

}